# -*- coding: utf-8 -*-
"""MachineLearning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zdob_hnKi_jT0E12ANy2ekrkoV42-C4u
"""

import pandas as pd
data={
    "Name":["Preeti","Prajval","Prem"],
    "USN":["1BM22CS208","1BM22CS220","1BM22CS341"],
    "Grade":["O","S","A+"]
}
df=pd.DataFrame(data,index=[1,2,3])
df

from sklearn.datasets import load_iris
iris=load_iris()
df=pd.DataFrame(iris.data,columns=iris.feature_names)
df['target']=iris.target_names[iris.target]
df.head()

file_path='/content/sample_data/california_housing_train.csv'
df=pd.read_csv(file_path)
df.head()

df = pd.read_csv('/content/Dataset of Diabetes .csv')
print("Sample data:")
df.head()

import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt

tickers = ["RELIANCE.NS", "TCS.NS", "INFY.NS"]
data = yf.download(tickers, start="2022-10-01", end="2023-10-01",group_by='ticker')
print("First 5 rows of the dataset:")
print(data.head())
print("\nShape of the dataset:")
print(data.shape)
print("\nColumn names:")
print(data.columns)
reliance_data = data['RELIANCE.NS']
print("\nSummary statistics for Reliance Industries:")
print(reliance_data.describe())
reliance_data['Daily Return'] = reliance_data['Close'].pct_change()
plt.figure(figsize=(12, 6))
plt.subplot(2, 1, 1)
reliance_data['Close'].plot(title="Reliance Industries - Closing Price")
plt.subplot(2, 1, 2)
reliance_data['Daily Return'].plot(title="Reliance Industries - Daily Returns", color='orange')
plt.tight_layout()
plt.show()
reliance_data.to_csv('reliance_stock_data.csv')
print("\nReliance stock data saved to 'reliance_stock_data.csv'.")

